GET http://localhost:3000/users

### creating new users

POST  http://localhost:3000/users
Content-Type: application/json

{
    "userName": "jafeershaik",
    "firstName": "Jafeer",
    "lastName": "Shaik",
    "age":23,
    "phone":"9700853426",
    "address":"nellore"
}

###updating user
PUT   http://localhost:3000/users
Content-Type: application/json

{
    "_id":"65423d4b726df47fcbaa1e08",
    "userName": "jafeershaik",
    "firstName": "Jafeer",
    "lastName": "Shaik",
    "age":23,
    "phone":"9700853426",
    "address":{
            "doorNo":"28-5-4",
            "street":"putta center",
            "area":"mypadu road",
            "city":"nellore",
            "state":"Andhra Pradesh",
            "country":"india",
            "zipcode":524002
        }
    
}

### get a particular user

GET http://localhost:3000/users/65423d4b726df47fcbaa1e08
