###Getting the users.

GET http://localhost:4040/users

### creating new users.

POST  http://localhost:4040/users
Content-Type: application/json

{
    "userName": "MSD",
    "firstName": "Mahendra Singh",
    "lastName": "Dhoni",
    "age":42,
    "phone":"1234567890",
    "address":{
            "doorNo":"12-3-4",
            "street":"street",
            "area":"Ranchi",
            "city":"Ranchi",
            "state":"Jharkhand",
            "country":"India",
            "zipcode":123456
        }
    
}

###updating user
PUT   http://localhost:4040/users
Content-Type: application/json

{
    "_id":"654345c7bcac27a210c6e47c",
    "userName": "fooBoo",
    "firstName": "Foo",
    "lastName": "Boo",
    "age":23,
    "phone":"1234567890",
    "address":{
            "doorNo":"1-2-3",
            "street":"street",
            "area":"area",
            "city":"city",
            "state":"Andhra Pradesh",
            "country":"India",
            "zipcode":123456
        }
    
}

### get a particular user
### you can add your objectId here in params

GET http://localhost:4040/users/654345c7bcac27a210c6e47c

### delete a particular user

DELETE  http://localhost:4040/users/654345c7bcac27a210c6e47c